name 'dev-mac-setup'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dev-mac-setup'
long_description 'Installs/Configures dev-mac-setup'
version '0.1.0'
